<?php
	date_default_timezone_set('Asia/Ho_Chi_Minh');
    include_once("connect.php");
    include_once("crud.php");
    include_once("crud_v2.php");
    include_once("auth.php");
    include_once("another.php");
    include_once("ajax.php");
?>