<?php
    include_once("connect.php");
    include_once("crud.php");
    include_once("crud_v2.php");
    include_once("api.php");
    include_once("auth.php");
    include_once("another.php");
    include_once("ajax.php");
    include_once("file.php");
?>